VOC_REASONING_MODEL_USE_CASE = "voc_reasoning"

OPENAI_TRANSCRIPTION_MODEL_USE_CASE = "audio_transcription"

VOC_PROCESSING_TRIGGER = "new_customer_communication"

EMBEDDING_THRESHOLD = 0.70

DEFAULT_CONFIDENCE = 0.75
